// Config ESLint minimale : détecte les VRAIS bugs, ignore le style.
// Le code front est multi-fichiers avec des globals croisés (window.*),
// donc no-undef / no-unused-vars resteraient trop bruyants -> désactivés.
export default [
  {
    files: ['js/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        localStorage: 'readonly',
        navigator: 'readonly',
        console: 'readonly',
        fetch: 'readonly',
        Chart: 'readonly',
        L: 'readonly',
        flatpickr: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        MutationObserver: 'readonly',
        FileReader: 'readonly',
        DOMParser: 'readonly',
        URLSearchParams: 'readonly',
        Blob: 'readonly',
        performance: 'readonly',
        matchMedia: 'readonly',
        getComputedStyle: 'readonly',
        alert: 'readonly',
        confirm: 'readonly',
        CustomEvent: 'readonly',
        Event: 'readonly',
      },
    },
    rules: {
      // Vrais bugs uniquement
      'no-dupe-args': 'error',
      'no-dupe-keys': 'error',
      'no-dupe-else-if': 'error',
      'no-duplicate-case': 'error',
      'no-unreachable': 'error',
      'no-const-assign': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': ['error', 'except-parens'],
      'no-constant-condition': ['error', { checkLoops: false }],
      'no-self-assign': 'error',
      'no-self-compare': 'error',
      'no-unsafe-negation': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
      'no-func-assign': 'error',
      'no-obj-calls': 'error',
      'no-sparse-arrays': 'error',
      'getter-return': 'error',
      'no-setter-return': 'error',
      'no-async-promise-executor': 'error',
      'no-debugger': 'error',
    },
  },
];
